spring:
   datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@lisanstudy.cjb2viqvjmpg.us-east-2.rds.amazonaws.com:1521:orcl
      username: LisanStudy
      password: 1san1san
   mvc:
      view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
      static-path-pattern: /resources/**

mybatis:
  type-aliases-package: com.ilsan.myggumi.web.domain
  mapper-locations: classpath:mappers/*.xml
  configuration:
    default-statement-timeout: 120

logging:
  level:
    org.springframework.web: DEBUG
    com.ilsan.myggumi.web: DEBUG
      
server:
  context-path: /
  port: 9092




